language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.8.7
install:
  - pip install --upgrade pip
  - pip install -q Django==$DJANGO
  - pip install coveralls
script:
  - coverage run --source=. runtests.py
after_success:
  - coveralls
