# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('alter_name', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField()),
                ('vnum', models.IntegerField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name', 'level'],
            },
        ),
        migrations.CreateModel(
            name='ZoneLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '\u041f\u0435\u0448\u043a\u043e\u043c'), (1, '\u041f\u0435\u0440\u0435\u0445\u043e\u0434 \u0437\u0430 \u0434\u0435\u043d\u044c\u0433\u0438'), (2, '\u041f\u0435\u0440\u0435\u0445\u043e\u0434 \u0442\u0440\u0438\u0433\u0433\u0435\u0440\u043e\u043c'), (3, '\u0422\u0435\u043b\u0435\u043f\u043e\u0440\u0442 \u0437\u0430 \u0438\u043d\u0433\u0440\u0438\u0434\u0438\u0435\u043d\u0442\u044b'), (4, '\u0422\u0435\u043b\u0435\u043f\u043e\u0440\u0442 \u0437\u0430 \u0434\u0435\u043d\u044c\u0433\u0438')], default=0)),
                ('value', models.TextField(blank=True)),
                ('z1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_zones', to='zones.Zone')),
                ('z2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zones.Zone')),
            ],
        ),
    ]
