# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('short_name', models.TextField()),
                ('active', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SquadActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='squad.Squad')),
            ],
        ),
        migrations.CreateModel(
            name='SquadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('population', models.IntegerField()),
                ('exp_total', models.BigIntegerField()),
                ('exp_30', models.BigIntegerField()),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='squad.Squad')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
