language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install coveralls
script:
  - coverage run --source=. run_tests.py
after_success:
  - coveralls