# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
                ('type', models.IntegerField(choices=[(0, '\u041e\u0444\u0444\u0442\u043e\u043f'), (1, '\u0411\u043e\u043b\u0442\u0430\u0442\u044c'), (2, '\u041e\u0440\u0430\u0442\u044c')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
    ]
