# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 17:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 9, 16, 17, 7, 51, 957016))),
                ('mud_date', models.DateTimeField()),
                ('mud_num', models.IntegerField()),
                ('title', models.TextField()),
                ('title_safe', models.TextField(null=True)),
                ('text', models.TextField()),
                ('text_safe', models.TextField(null=True)),
                ('type', models.IntegerField(choices=[(0, '\u041d\u043e\u0432\u043e\u0441\u0442\u0438'), (1, '\u0412\u0435\u0447\u0435'), (2, '\u0410\u043d\u043e\u043d\u0441\u044b'), (3, '\u0418\u0434\u0435\u0438'), (4, '\u041a\u043e\u0434\u0435\u0440')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
    ]
