# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 16:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 19, 16, 52, 2, 612992)),
        ),
    ]
